### ISSUE TITLE
Prints out Fibonacci "SEQUENCE" instead of Fibonacci "SERIES"

### ISSUE THREAD

**Issue by prateekkhanal** [Manishshtestha/C-programming-for-Beginners#1]
In the *[fibonacci_series.c](https://github.com/Manishshtestha/C-programming-for-Beginners/blob/main/fibonacci_series.c)*, The output seperates the individual numbers by "**,**"  instead of "**+**".

**Comment by Manishshtestha** [comment]
I'm Busy right now, Feel free to mend the code and send a PR

**Comment by Manishshtestha** [comment]
Thanks for your contibution🤗
